services:
  rails:
    build:
      context: ./rails
    command: "bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/myapp
    depends_on:
      - db
    tty: true
    stdin_open: true
  react:
    build:
      dockerfile: ./react/Dockerfile
    command: sh -c "npm install && npm run dev"
    tty: true
    stdin_open: true
    volumes:
      - ./react:/app
    ports:
      - "5173:5173"
  db:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=react_rails_shop_development
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
